version: '3.8'
services:
  app:
    image: sloopstash/node-js-app:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "8080:80"
    volumes:
      - ../app:/opt/app/source
      - ../supervisor/conf/app.ini:/etc/supervisord.d/app.ini
      - ../../supervisor/conf/main.conf:/etc/supervisord.conf
    depends_on:
      - mongo-db
    networks:
      common:
        ipv4_address: 100.1.1.10
  mongo-db:
    image: sloopstash/mongo-db:v1 
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    volumes:
      - mongo-db-data:/opt/mongo-db/data
      - mongo-db-log:/opt/mongo-db/log
      - ../mongo-db/conf/mongod.conf:/opt/mongo-db/conf/mongod.conf
      - ../supervisor/conf/mongo-db.ini:/etc/supervisord.d/mongo-db.ini
      - ../../supervisor/conf/main.conf:/etc/supervisord.conf
    networks:
      common:
        ipv4_address: 100.1.1.20
volumes:
  mongo-db-data:
    driver: local
  mongo-db-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.1.0.0/16